/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.ParticipanteDAO;
import com.mycompany.futbolito.modelos.Participante;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author Usuario
 */
public class VistaParticipante extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaParticipante
     */
// Variable para saber qué wey seleccionaste de la tabla
    private long idParticipanteSeleccionado = -1;

    public VistaParticipante() {
        initComponents();
        
        // Agregamos el evento del clic a la tabla manualmente
        tablaParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaParticipantesMouseClicked(evt);
            }
        });

        // Cargamos los datos iniciales
        cargarTabla();
        limpiarCampos();
    }
    
    private void cargarTabla() {
        try {
            ParticipanteDAO dao = new ParticipanteDAO();
            tablaParticipantes.setModel(dao.obtenerModeloParticipantes());

            // --- CÓDIGO NUEVO PARA EL ANCHO DE COLUMNAS ---
            // El número es la columna (0 es ID, 1 es Nombre, etc.) y el setPreferredWidth es el tamaño en píxeles.
            tablaParticipantes.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
            tablaParticipantes.getColumnModel().getColumn(1).setPreferredWidth(200); // Nombre (Más ancho)
            tablaParticipantes.getColumnModel().getColumn(2).setPreferredWidth(100); // Género
            tablaParticipantes.getColumnModel().getColumn(3).setPreferredWidth(120); // Teléfono
            tablaParticipantes.getColumnModel().getColumn(4).setPreferredWidth(200); // Correo
            tablaParticipantes.getColumnModel().getColumn(5).setPreferredWidth(120); // Fecha
            tablaParticipantes.getColumnModel().getColumn(6).setPreferredWidth(50);  // Edad

            // Opcional: Evitar que el usuario cambie el orden de las columnas arrastrándolas
            tablaParticipantes.getTableHeader().setReorderingAllowed(false);

        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtCorreo.setText("");
        txtNumero.setText(""); // Ojo: A tu campo de teléfono le pusiste txtNumero
        cbGenero.setSelectedIndex(0);
        calendario.setDate(new Date()); // Lo regresa a la fecha de hoy
        
        idParticipanteSeleccionado = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JCalendar();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaParticipantes = new javax.swing.JTable();

        panelInputs.setBackground(new java.awt.Color(204, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Correo electrónico:");

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Género:");

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Teléfono:");

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInputsLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNumero))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)))
                .addGap(92, 92, 92)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(34, 34, 34)
                        .addComponent(btnModificar)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminar))
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        panelDatos.setBackground(new java.awt.Color(255, 51, 51));

        tablaParticipantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaParticipantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaParticipantes.setRowHeight(30);
        tablaParticipantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaParticipantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaParticipantes);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInputs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String telefono = txtNumero.getText().trim();
        String correo = txtCorreo.getText().trim();
        String genero = cbGenero.getSelectedItem().toString();
        Date fechaSeleccionada = calendario.getDate();

        // Validaciones tontas (Visuales)
        if (nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty() || fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (telefono.length() < 10) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de teléfono válido (mínimo 10 dígitos).", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!correo.contains("@") || !correo.contains(".")) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo electrónico válido.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Participante p = new Participante();
        p.setNombre(nombre);
        p.setGenero(genero);
        p.setTelefono(telefono);
        p.setCorreo(correo);
        p.setFechaNacimiento(new java.sql.Date(fechaSeleccionada.getTime()));

        try {
            ParticipanteDAO dao = new ParticipanteDAO();
            dao.insertarParticipante(p);
            JOptionPane.showMessageDialog(this, "Participante agregado exitosamente.");
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idParticipanteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un participante de la tabla para modificar.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = txtNombre.getText().trim();
        String telefono = txtNumero.getText().trim();
        String correo = txtCorreo.getText().trim();
        String genero = cbGenero.getSelectedItem().toString();
        Date fechaSeleccionada = calendario.getDate();

        if (nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty() || fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Participante p = new Participante();
        p.setIdParticipante(idParticipanteSeleccionado);
        p.setNombre(nombre);
        p.setGenero(genero);
        p.setTelefono(telefono);
        p.setCorreo(correo);
        p.setFechaNacimiento(new java.sql.Date(fechaSeleccionada.getTime()));

        try {
            ParticipanteDAO dao = new ParticipanteDAO();
            dao.modificarParticipante(p);
            JOptionPane.showMessageDialog(this, "Participante modificado exitosamente.");
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idParticipanteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un participante para eliminar.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Una confirmación nunca está de más antes de borrar
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres eliminar este participante?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                ParticipanteDAO dao = new ParticipanteDAO();
                dao.eliminarParticipante(idParticipanteSeleccionado);
                JOptionPane.showMessageDialog(this, "Participante eliminado exitosamente.");
                cargarTabla();
                limpiarCampos();
            } catch (Exception ex) {
                ManejadorErroresBD.mostrarErrorAmigable(ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaParticipantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaParticipantesMouseClicked
        int fila = tablaParticipantes.getSelectedRow();
        if (fila >= 0) {
            try {
                idParticipanteSeleccionado = Long.parseLong(tablaParticipantes.getValueAt(fila, 0).toString());
                txtNombre.setText(tablaParticipantes.getValueAt(fila, 1).toString());
                cbGenero.setSelectedItem(tablaParticipantes.getValueAt(fila, 2).toString());
                txtNumero.setText(tablaParticipantes.getValueAt(fila, 3).toString());
                txtCorreo.setText(tablaParticipantes.getValueAt(fila, 4).toString());
                
                // Convertimos el java.sql.Date de la tabla a java.util.Date para el JCalendar
                java.sql.Date fechaSQL = (java.sql.Date) tablaParticipantes.getValueAt(fila, 5);
                calendario.setDate(new java.util.Date(fechaSQL.getTime()));
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar los datos de la tabla: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tablaParticipantesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JTable tablaParticipantes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
