/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.ResultadoPartidoDAO;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Calendar;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;

/**
 *
 * @author Usuario
 */
public class VistaResultadoPartido extends javax.swing.JInternalFrame {

    private long idResultadoSeleccionado = -1;
    private long idPartidoFK = -1; // El partido que nos pasan desde la otra ventana
    private long idPartidoSeleccionado = -1; // Para la modificación

    /**
     * Creates new form VistaResultadoPartido
     */
    public VistaResultadoPartido() {
        initComponents();
        configurarVentana();
    }

    // Constructor SOBRECARGADO para cuando lo llamemos desde VistaPartido
    public VistaResultadoPartido(long idPartidoRecibido) {
        initComponents();
        configurarVentana();

        this.idPartidoFK = idPartidoRecibido;
        try {
            ResultadoPartidoDAO dao = new ResultadoPartidoDAO();
            txtEquipo.setText(dao.obtenerDetallePartido(this.idPartidoFK));
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void configurarVentana() {
        // Configuramos la hora
        horaTermino.setModel(new SpinnerDateModel());
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(horaTermino, "HH:mm");
        horaTermino.setEditor(timeEditor);

        // Bloqueamos los goles (Requisito de la maestra de iniciar siempre en 0)
        golesLocal.setValue(0);
        golesLocal.setEnabled(false);
        golesVisitante.setValue(0);
        golesVisitante.setEnabled(false);

        tablaPartidos.setRowHeight(30);

        cargarTabla();
        limpiarCampos();
    }

    private void cargarTabla() {
        try {
            ResultadoPartidoDAO dao = new ResultadoPartidoDAO();
            tablaPartidos.setModel(dao.obtenerModeloResultados());

            // Ocultamos IdResultado e IdPartido
            /*tablaPartidos.getColumnModel().getColumn(0).setMinWidth(0);
            tablaPartidos.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaPartidos.getColumnModel().getColumn(0).setWidth(0);*/
            tablaPartidos.getColumnModel().getColumn(1).setMinWidth(0);
            tablaPartidos.getColumnModel().getColumn(1).setMaxWidth(0);
            tablaPartidos.getColumnModel().getColumn(1).setWidth(0);

            tablaPartidos.getTableHeader().setReorderingAllowed(false);
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarColumnas(tablaPartidos);

        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        idResultadoSeleccionado = -1;
        idPartidoSeleccionado = -1;

        // Si no nos pasaron un partido, limpiamos la caja
        if (idPartidoFK == -1) {
            txtEquipo.setText("");
        }

        golesLocal.setValue(0);
        golesVisitante.setValue(0);

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 14); // Hora por defecto 14:00
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        horaTermino.setValue(cal.getTime());
        actualizarBotones(false);
    }

    private java.sql.Time extraerHoraLimpia() {
        Calendar cal = Calendar.getInstance();
        cal.setTime((Date) horaTermino.getValue());
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        return new java.sql.Time(cal.getTimeInMillis());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        golesLocal = new javax.swing.JSpinner();
        golesVisitante = new javax.swing.JSpinner();
        horaTermino = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartidos = new javax.swing.JTable();
        btnRegGoles = new javax.swing.JButton();
        btnRegTarjetas = new javax.swing.JButton();

        setTitle("ResultadoPartido");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Partido:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Goles equipo local:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Goles equipo visitante:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Hora de término:");

        txtEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEquipo.setEnabled(false);

        golesLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        golesVisitante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        horaTermino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tablaPartidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPartidos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegGoles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegGoles.setText("Registrar goles");
        btnRegGoles.addActionListener(this::btnRegGolesActionPerformed);

        btnRegTarjetas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegTarjetas.setText("Registrar tarjetas");
        btnRegTarjetas.addActionListener(this::btnRegTarjetasActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(golesVisitante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(golesLocal, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(759, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(horaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegGoles)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegTarjetas)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(golesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(golesVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegGoles)
                    .addComponent(btnRegTarjetas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (idPartidoFK == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Partido desde el formulario de Partidos para agregar un resultado.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Time sqlHoraFin = extraerHoraLimpia();

        try {
            ResultadoPartidoDAO dao = new ResultadoPartidoDAO();

            if (dao.verificaHoraFinInicio(idPartidoFK, sqlHoraFin)) {
                JOptionPane.showMessageDialog(this, "La hora de término no puede ser antes o igual a la de inicio del partido.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.insertarResultado(idPartidoFK, sqlHoraFin);
            cargarTabla();

            // Ya registrado, limpiamos el FK para obligar a seleccionar otro partido nuevo
            idPartidoFK = -1;
            limpiarCampos();

        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idResultadoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un resultado de la tabla para modificar.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Time sqlHoraFin = extraerHoraLimpia();

        try {
            ResultadoPartidoDAO dao = new ResultadoPartidoDAO();

            // Validamos contra el partido seleccionado de la fila
            if (dao.verificaHoraFinInicio(idPartidoSeleccionado, sqlHoraFin)) {
                JOptionPane.showMessageDialog(this, "La hora de término no puede ser antes o igual a la de inicio del partido.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.modificarResultado(idResultadoSeleccionado, sqlHoraFin);
            cargarTabla();
            limpiarCampos();

        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idResultadoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Resultado para eliminar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            ResultadoPartidoDAO dao = new ResultadoPartidoDAO();
            dao.eliminarResultado(idResultadoSeleccionado);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPartidosMouseClicked
        int fila = tablaPartidos.getSelectedRow();
        if (fila >= 0) {
            try {
                idResultadoSeleccionado = Long.parseLong(tablaPartidos.getValueAt(fila, 0).toString());
                idPartidoSeleccionado = Long.parseLong(tablaPartidos.getValueAt(fila, 1).toString());

                txtEquipo.setText(tablaPartidos.getValueAt(fila, 2).toString());

                // Estos spinners están bloqueados, pero actualizamos su valor para que se vean los goles actuales
                golesLocal.setValue(Integer.parseInt(tablaPartidos.getValueAt(fila, 3).toString()));
                golesVisitante.setValue(Integer.parseInt(tablaPartidos.getValueAt(fila, 4).toString()));

                java.sql.Time horaSQL = (java.sql.Time) tablaPartidos.getValueAt(fila, 5);
                horaTermino.setValue(new java.util.Date(horaSQL.getTime()));
                actualizarBotones(true);

            } catch (Exception ex) {
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_tablaPartidosMouseClicked

    private void btnRegGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegGolesActionPerformed
        VistaGol ventanaGol = new VistaGol(idPartidoSeleccionado);

        // 2. Extraes el escritorio padre
        javax.swing.JDesktopPane escritorio = this.getDesktopPane();

        // 3. Limpias el escritorio (destruye VistaParticipante)
        escritorio.removeAll();
        escritorio.repaint();

        // 4. Agregas la de Jugador y la maximizas
        escritorio.add(ventanaGol);
        ventanaGol.setVisible(true);
        try {
            ventanaGol.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRegGolesActionPerformed

    private void btnRegTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTarjetasActionPerformed
        VistaTarjeta ventanaTarjeta = new VistaTarjeta(idPartidoSeleccionado);

        // 2. Extraes el escritorio padre
        javax.swing.JDesktopPane escritorio = this.getDesktopPane();

        // 3. Limpias el escritorio (destruye VistaParticipante)
        escritorio.removeAll();
        escritorio.repaint();

        // 4. Agregas la de Jugador y la maximizas
        escritorio.add(ventanaTarjeta);
        ventanaTarjeta.setVisible(true);
        try {
            ventanaTarjeta.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRegTarjetasActionPerformed

    private void actualizarBotones(boolean mostrar) {
        btnRegGoles.setEnabled(mostrar);
        btnRegTarjetas.setEnabled(mostrar);

        btnRegGoles.setVisible(mostrar);
        btnRegTarjetas.setVisible(mostrar);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegGoles;
    private javax.swing.JButton btnRegTarjetas;
    private javax.swing.JSpinner golesLocal;
    private javax.swing.JSpinner golesVisitante;
    private javax.swing.JSpinner horaTermino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPartidos;
    private javax.swing.JTextField txtEquipo;
    // End of variables declaration//GEN-END:variables
}
