/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.DetalleTorneoDAO;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class VistaDetalleTorneo extends javax.swing.JInternalFrame {
    // Listas paralelas para guardar los IDs de los ComboBoxes
    private List<Long> idsTorneos = new ArrayList<>();
    private List<Long> idsEquipos = new ArrayList<>();
    
    // Guardamos la llave primaria compuesta anterior para el UPDATE
    private long idTorneoViejo = -1;
    private long idEquipoViejo = -1;
    
    /**
     * Creates new form VistaDetalleTorneo
     */
    public VistaDetalleTorneo() {
        initComponents();
        
        tablaDetalleTorneo.setRowHeight(30);
        
        cargarCombos();
        cargarTabla();
        limpiarCampos();
    }
    
    private void cargarCombos() {
        try {
            DetalleTorneoDAO dao = new DetalleTorneoDAO();
            
            // Cargar Torneos
            cbTorneo.removeAllItems();
            idsTorneos.clear();
            for (DetalleTorneoDAO.ItemCombo item : dao.obtenerTorneosCombo()) {
                cbTorneo.addItem(item.texto);
                idsTorneos.add(item.id);
            }
            cbTorneo.setSelectedIndex(-1);
            
            // Cargar Equipos
            cbEquipo.removeAllItems();
            idsEquipos.clear();
            for (DetalleTorneoDAO.ItemCombo item : dao.obtenerEquiposCombo()) {
                cbEquipo.addItem(item.texto);
                idsEquipos.add(item.id);
            }
            cbEquipo.setSelectedIndex(-1);
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void cargarTabla() {
        try {
            DetalleTorneoDAO dao = new DetalleTorneoDAO();
            tablaDetalleTorneo.setModel(dao.obtenerModeloDetalleTorneo());
            
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarColumnas(tablaDetalleTorneo);
            
            // Ocultar las columnas técnicas tal como en tu C#
            int[] columnasOcultas = {0, 1, 4, 5};
            for (int col : columnasOcultas) {
                tablaDetalleTorneo.getColumnModel().getColumn(col).setMinWidth(0);
                tablaDetalleTorneo.getColumnModel().getColumn(col).setMaxWidth(0);
                tablaDetalleTorneo.getColumnModel().getColumn(col).setWidth(0);
            }
            
            tablaDetalleTorneo.getTableHeader().setReorderingAllowed(false);
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        cbTorneo.setSelectedIndex(-1);
        cbEquipo.setSelectedIndex(-1);
        idTorneoViejo = -1;
        idEquipoViejo = -1;
    }

    // Método para refrescar el formulario de Jornadas si está abierto en el menú principal
    private void notificarCambioAJornada() {
        if (this.getDesktopPane() != null) {
            for (javax.swing.JInternalFrame frame : this.getDesktopPane().getAllFrames()) {
                if (frame instanceof VistaJornada) {
                    ((VistaJornada) frame).cargarTabla();
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTorneo = new javax.swing.JComboBox<>();
        cbEquipo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleTorneo = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Torneo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Equipo:");

        cbTorneo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbEquipo, 0, 500, Short.MAX_VALUE)
                    .addComponent(cbTorneo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(37, 37, 37))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));

        tablaDetalleTorneo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaDetalleTorneo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDetalleTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleTorneoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDetalleTorneo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (cbTorneo.getSelectedIndex() == -1 || cbEquipo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un torneo y un equipo", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long idTorneoNuevo = idsTorneos.get(cbTorneo.getSelectedIndex());
        long idEquipoNuevo = idsEquipos.get(cbEquipo.getSelectedIndex());

        try {
            DetalleTorneoDAO dao = new DetalleTorneoDAO();
            
            if (dao.existeDetalle(idTorneoNuevo, idEquipoNuevo)) {
                JOptionPane.showMessageDialog(this, "Este equipo ya está inscrito en el torneo", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.insertarDetalle(idTorneoNuevo, idEquipoNuevo);
            
            cargarTabla();
            limpiarCampos();
            notificarCambioAJornada(); // Actualizamos la vista de Jornada
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idTorneoViejo == -1 || idEquipoViejo == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cbTorneo.getSelectedIndex() == -1 || cbEquipo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un torneo y un equipo", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long idTorneoNuevo = idsTorneos.get(cbTorneo.getSelectedIndex());
        long idEquipoNuevo = idsEquipos.get(cbEquipo.getSelectedIndex());

        try {
            DetalleTorneoDAO dao = new DetalleTorneoDAO();
            
            if (dao.existeDetalleModificar(idTorneoNuevo, idEquipoNuevo, idTorneoViejo, idEquipoViejo)) {
                JOptionPane.showMessageDialog(this, "Ya existe ese equipo en ese torneo", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.modificarDetalle(idTorneoNuevo, idEquipoNuevo, idTorneoViejo, idEquipoViejo);
            
            cargarTabla();
            limpiarCampos();
            notificarCambioAJornada();
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idTorneoViejo == -1 || idEquipoViejo == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DetalleTorneoDAO dao = new DetalleTorneoDAO();
            dao.eliminarDetalle(idTorneoViejo, idEquipoViejo);
            
            cargarTabla();
            limpiarCampos();
            notificarCambioAJornada();
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaDetalleTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleTorneoMouseClicked
        int fila = tablaDetalleTorneo.getSelectedRow();
        if (fila >= 0) {
            try {
                // Sacamos los IDs de la tabla (columnas ocultas 0 y 1)
                idTorneoViejo = Long.parseLong(tablaDetalleTorneo.getValueAt(fila, 0).toString());
                idEquipoViejo = Long.parseLong(tablaDetalleTorneo.getValueAt(fila, 1).toString());
                
                // Buscamos en qué índice de nuestras listas paralelas están estos IDs
                int indexTorneo = idsTorneos.indexOf(idTorneoViejo);
                int indexEquipo = idsEquipos.indexOf(idEquipoViejo);
                
                // Asignamos esos índices a los ComboBox
                if (indexTorneo != -1) cbTorneo.setSelectedIndex(indexTorneo);
                if (indexEquipo != -1) cbEquipo.setSelectedIndex(indexEquipo);
                
            } catch (Exception ex) {
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_tablaDetalleTorneoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbEquipo;
    private javax.swing.JComboBox<String> cbTorneo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalleTorneo;
    // End of variables declaration//GEN-END:variables
}
