/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.EquipoDAO;
import com.mycompany.futbolito.modelos.Equipo;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;

/**
 *
 * @author Usuario
 */
public class VistaEquipo extends javax.swing.JInternalFrame {
    private long idEquipoSeleccionado = -1;
    /**
     * Creates new form VistaEquipo
     */
    public VistaEquipo() {
        initComponents();
        
        // El mismo alto de fila que tenías en C# (60) para que quepa la imagen bien
        tablaEquipos.setRowHeight(60);
        
        cargarTabla();
        limpiarCampos();
    }
    
    private void cargarTabla() {
        try {
            EquipoDAO dao = new EquipoDAO();
            tablaEquipos.setModel(dao.obtenerModeloEquipos());
            
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarColumnas(tablaEquipos);
            
            // Configuramos la columna de la Imagen para que tenga un ancho de 80
            tablaEquipos.getColumnModel().getColumn(2).setPreferredWidth(80);
            
            // Ocultamos la columna 4 (que trae el texto de la URL)
            tablaEquipos.getColumnModel().getColumn(4).setMinWidth(0);
            tablaEquipos.getColumnModel().getColumn(4).setMaxWidth(0);
            tablaEquipos.getColumnModel().getColumn(4).setWidth(0);
            
            tablaEquipos.getTableHeader().setReorderingAllowed(false);
            
            // LA MAGIA DE JAVA: Llamamos a la descarga de imágenes en el fondo
            cargarImagenesAsincrono();
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    // Equivale a tu "async void cargaEquipos()" en C#
    private void cargarImagenesAsincrono() {
        Thread hiloDescarga = new Thread(() -> {
            for (int i = 0; i < tablaEquipos.getRowCount(); i++) {
                // Sacamos la URL de la columna 4 (la oculta)
                String urlTexto = (String) tablaEquipos.getModel().getValueAt(i, 4);
                
                if (urlTexto != null && !urlTexto.isEmpty()) {
                    try {
                        URL url = new URL(urlTexto);
                        
                        // --- EL TRUCO DEL USER-AGENT ---
                        java.net.HttpURLConnection conexionHttp = (java.net.HttpURLConnection) url.openConnection();
                        // Nos disfrazamos de navegador de Windows para que Wikipedia no nos bloquee
                        conexionHttp.addRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36");
                        
                        // Leemos la imagen pero desde nuestra conexión disfrazada
                        Image img = ImageIO.read(conexionHttp.getInputStream());
                        // -------------------------------
                        
                        if (img != null) {
                            Image imgEscalada = img.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                            ImageIcon icono = new ImageIcon(imgEscalada);
                            
                            final int filaActual = i;
                            javax.swing.SwingUtilities.invokeLater(() -> {
                                tablaEquipos.getModel().setValueAt(icono, filaActual, 2);
                            });
                        }
                    } catch (Exception e) {
                        System.out.println("Error descargando imagen de " + urlTexto + ": " + e.getMessage());
                    }
                }
            }
        });
        
        // Arrancamos el hilo secundario
        hiloDescarga.start();
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtUrl.setText("");
        idEquipoSeleccionado = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEquipos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("URL del logotipo:");

        txtUrl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrlKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre)
                    .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addGap(32, 32, 32)
                        .addComponent(btnEliminar)
                        .addGap(14, 14, 14))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        tablaEquipos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEquipos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String logo = txtUrl.getText().trim();

        if (nombre.isEmpty() || logo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            EquipoDAO dao = new EquipoDAO();
            
            if (dao.existeNombreEquipo(nombre, -1)) {
                JOptionPane.showMessageDialog(this, "Ya existe un equipo con ese nombre.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Equipo e = new Equipo();
            e.setNombreEquipo(nombre);
            e.setLogo(logo);

            dao.insertarEquipo(e);
            // Sin mensaje de confirmación
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idEquipoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Equipo para modificar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = txtNombre.getText().trim();
        String logo = txtUrl.getText().trim();

        if (nombre.isEmpty() || logo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            EquipoDAO dao = new EquipoDAO();
            
            if (dao.existeNombreEquipo(nombre, idEquipoSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Ya existe un equipo con ese nombre.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Equipo e = new Equipo();
            e.setIdEquipo(idEquipoSeleccionado);
            e.setNombreEquipo(nombre);
            e.setLogo(logo);

            dao.modificarEquipo(e);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idEquipoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Equipo para eliminar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Eliminación directa sin confirmación
        try {
            EquipoDAO dao = new EquipoDAO();
            dao.eliminarEquipo(idEquipoSeleccionado);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquiposMouseClicked
        int fila = tablaEquipos.getSelectedRow();
        if (fila >= 0) {
            try {
                idEquipoSeleccionado = Long.parseLong(tablaEquipos.getValueAt(fila, 0).toString());
                txtNombre.setText(tablaEquipos.getValueAt(fila, 1).toString());
                
                // La columna 2 es la imagen, la 3 son los jugadores, la 4 es el texto de la URL
                txtUrl.setText(tablaEquipos.getValueAt(fila, 4).toString());
                
            } catch (Exception ex) {
                // Si hay error, simplemente limpiamos como tenías en C#
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_tablaEquiposMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() >= 50)
            evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtUrlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlKeyTyped
        if (txtUrl.getText().length() >= 500)
            evt.consume();
    }//GEN-LAST:event_txtUrlKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEquipos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
