/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.ArbitroDAO;
import com.mycompany.futbolito.dao.ParticipanteDAO;
import com.mycompany.futbolito.modelos.Arbitro;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VistaArbitro extends javax.swing.JInternalFrame {
    private long idArbitroSeleccionado = -1;
    private long idParticipanteHeredado = -1;
    /**
     * Creates new form VistaArbitro
     */
    public VistaArbitro() {
        this(-1);
    }
    
    public VistaArbitro(long id) {
        initComponents();
        this.idParticipanteHeredado = id;
        cargarTabla();
        // Ajustamos la altura de las filas para que no se vea aplastado
        tablaArbitros.setRowHeight(30);
        if (idParticipanteHeredado != -1) {
            btnAgregar.setEnabled(true);
            cargarNombreForaneo(idParticipanteHeredado);
        }
    }

    private void cargarNombreForaneo(long id) {
        try {
            ArbitroDAO dao = new ArbitroDAO();
            String nombre = dao.obtenerNombreParticipante(id);
            txtNombre.setText(nombre); 
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }
    
    private void cargarTabla() {
        try {
            ArbitroDAO dao = new ArbitroDAO();
            tablaArbitros.setModel(dao.obtenerModeloArbitros());
            
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarColumnas(tablaArbitros);
            
            // Ocultamos la columna 0 (IdParticipante)
            tablaArbitros.getColumnModel().getColumn(0).setMinWidth(0);
            tablaArbitros.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaArbitros.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaArbitros.getColumnModel().getColumn(0).setWidth(0);
            
            tablaArbitros.getTableHeader().setReorderingAllowed(false);
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        txtCedula.setText("");
        idArbitroSeleccionado = -1;
        
        if (idParticipanteHeredado == -1) {
            txtNombre.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArbitros = new javax.swing.JTable();

        panelInputs.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Árbitro:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cédula profesional:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setEnabled(false);

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addGap(32, 32, 32)
                .addComponent(btnEliminar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelDatos.setBackground(new java.awt.Color(102, 0, 51));

        tablaArbitros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaArbitros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArbitrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArbitros);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (idParticipanteHeredado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Participante desde el formulario de Participantes", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cedula = txtCedula.getText().trim();

        if (cedula.isEmpty() || cedula.length() < 15) {
            JOptionPane.showMessageDialog(this, "Ingrese la Cédula Profesional (Mínimo 15 caracteres).", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Reutilizamos el DAO de participante para revisar si ya es jugador (Tipo 1)
            ParticipanteDAO daoParticipante = new ParticipanteDAO();
            boolean esJugador = daoParticipante.yaEstaRegistradoComo(idParticipanteHeredado, 1);
            
            if (esJugador) {
                JOptionPane.showMessageDialog(this, "Este participante ya tiene el rol de Jugador, no puede ser Árbitro.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Arbitro a = new Arbitro();
            a.setIdParticipante(idParticipanteHeredado);
            a.setCedulaArbitro(cedula);

            ArbitroDAO dao = new ArbitroDAO();
            dao.insertarArbitro(a);
            
            //JOptionPane.showMessageDialog(this, "Árbitro agregado exitosamente.");
            
            idParticipanteHeredado = -1;
            //btnAgregar.setEnabled(false); 
            
            cargarTabla();
            limpiarCampos();
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idArbitroSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Árbitro para modificar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cedula = txtCedula.getText().trim();

        if (cedula.isEmpty() || cedula.length() < 15) {
            JOptionPane.showMessageDialog(this, "Ingrese la nueva Cédula Profesional (Mínimo 15 caracteres).", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Arbitro a = new Arbitro();
        a.setIdArbitro(idArbitroSeleccionado);
        a.setCedulaArbitro(cedula);

        try {
            ArbitroDAO dao = new ArbitroDAO();
            dao.modificarArbitro(a);
            //JOptionPane.showMessageDialog(this, "Árbitro modificado exitosamente.");
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idArbitroSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Árbitro para eliminar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            ArbitroDAO dao = new ArbitroDAO();
            dao.eliminarArbitro(idArbitroSeleccionado);
            //JOptionPane.showMessageDialog(this, "Árbitro eliminado exitosamente.");
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaArbitrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArbitrosMouseClicked
        int fila = tablaArbitros.getSelectedRow();
        if (fila >= 0) {
            try {
                // Columna 0 es IdParticipante, Columna 1 es IdArbitro
                idArbitroSeleccionado = Long.parseLong(tablaArbitros.getValueAt(fila, 1).toString());
                
                long idParticipanteDeTabla = Long.parseLong(tablaArbitros.getValueAt(fila, 0).toString());
                cargarNombreForaneo(idParticipanteDeTabla);
                
                txtCedula.setText(tablaArbitros.getValueAt(fila, 3).toString());
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar los datos de la tabla: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tablaArbitrosMouseClicked

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
    
        if (txtCedula.getText().length() >= 15) {
            evt.consume(); // Si ya hay 10 caracteres, ya no deja escribir más
        }
    }//GEN-LAST:event_txtCedulaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JTable tablaArbitros;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
