/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.TorneoDAO;
import com.mycompany.futbolito.modelos.Torneo;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import com.mycompany.futbolito.utilidades.SesionGlobal;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author Usuario
 */
public class VistaTorneo extends javax.swing.JInternalFrame {

    private long idTorneoSeleccionado = -1;

    /**
     * Creates new form VistaDetalleTorneo
     */
    public VistaTorneo() {
        initComponents();

        // Ajustamos la altura de las filas
        tablaTorneos.setRowHeight(30);
        cargarTabla();
        limpiarCampos();
        if (SesionGlobal.rol.equals("Capturista")) {
            btnAgregar.setVisible(false);
            btnModificar.setVisible(false);
            btnEliminar.setVisible(false);
        }
    }

    private void cargarTabla() {
        try {
            TorneoDAO dao = new TorneoDAO();
            tablaTorneos.setModel(dao.obtenerModeloTorneos());

            // Auto-ajustamos las columnas usando tu clase de utilidades
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarColumnas(tablaTorneos);
            tablaTorneos.getTableHeader().setReorderingAllowed(false);

        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        txtNombreTorneo.setText("");
        spinnerEdadMin.setValue(1);
        spinnerEdadMax.setValue(1);
        cbGenero.setSelectedIndex(0);
        fechaIni.setDate(new Date());
        fechaFin.setDate(new Date());
        idTorneoSeleccionado = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTorneo = new javax.swing.JTextField();
        spinnerEdadMin = new javax.swing.JSpinner();
        spinnerEdadMax = new javax.swing.JSpinner();
        cbGenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaIni = new com.toedter.calendar.JCalendar();
        fechaFin = new com.toedter.calendar.JCalendar();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTorneos = new javax.swing.JTable();

        setTitle("Torneo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del torneo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Edad mínima:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Edad máxima:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Género:");

        txtNombreTorneo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreTorneo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTorneoKeyTyped(evt);
            }
        });

        spinnerEdadMin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerEdadMin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spinnerEdadMax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerEdadMax.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de inicio:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de término:");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tablaTorneos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaTorneos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaTorneos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTorneosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTorneos);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerEdadMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(spinnerEdadMin, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
            .addComponent(panelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addComponent(txtNombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerEdadMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerEdadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInputsLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(37, 37, 37)
                        .addComponent(btnModificar)
                        .addGap(47, 47, 47)
                        .addComponent(btnEliminar))
                    .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombreTorneo.getText().trim();
        int edadMin = (int) spinnerEdadMin.getValue();
        int edadMax = (int) spinnerEdadMax.getValue();
        String genero = cbGenero.getSelectedItem().toString();

        // Convertimos a java.sql.Date directo para limpiar las horas y minutos (igual que .Date de C#)
        java.sql.Date fIni = new java.sql.Date(fechaIni.getDate().getTime());
        java.sql.Date fFin = new java.sql.Date(fechaFin.getDate().getTime());

        // Validaciones
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (edadMin > edadMax) {
            JOptionPane.showMessageDialog(this, "La edad mínima no puede ser mayor que la edad máxima", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // fIni.compareTo(fFin) > 0 significa que Inicio es DESPUÉS de Fin
        if (fIni.compareTo(fFin) > 0) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser posterior a la fecha de fin", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Usamos toString para comparar que no sean exactamente el mismo día
        if (fIni.toString().equals(fFin.toString())) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser igual a la fecha de fin", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Torneo t = new Torneo();
        t.setNombreTorneo(nombre);
        t.setEdadMin(edadMin);
        t.setEdadMax(edadMax);
        t.setGenero(genero);
        t.setFechaInicio(fIni);
        t.setFechaFin(fFin);

        try {
            TorneoDAO dao = new TorneoDAO();
            dao.insertarTorneo(t);
            // Sin mensaje de éxito
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idTorneoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Torneo para modificar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = txtNombreTorneo.getText().trim();
        int edadMin = (int) spinnerEdadMin.getValue();
        int edadMax = (int) spinnerEdadMax.getValue();
        String genero = cbGenero.getSelectedItem().toString();

        java.sql.Date fIni = new java.sql.Date(fechaIni.getDate().getTime());
        java.sql.Date fFin = new java.sql.Date(fechaFin.getDate().getTime());

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (edadMin > edadMax) {
            JOptionPane.showMessageDialog(this, "La edad mínima no puede ser mayor que la edad máxima", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (fIni.compareTo(fFin) > 0) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser posterior a la fecha de fin", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (fIni.toString().equals(fFin.toString())) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser igual a la fecha de fin", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Torneo t = new Torneo();
        t.setIdTorneo(idTorneoSeleccionado);
        t.setNombreTorneo(nombre);
        t.setEdadMin(edadMin);
        t.setEdadMax(edadMax);
        t.setGenero(genero);
        t.setFechaInicio(fIni);
        t.setFechaFin(fFin);

        try {
            TorneoDAO dao = new TorneoDAO();
            dao.modificarTorneo(t);
            // Sin mensaje de éxito
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idTorneoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Torneo para eliminar", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Se elimina sin confirmación, directo al DAO
        try {
            TorneoDAO dao = new TorneoDAO();
            dao.eliminarTorneo(idTorneoSeleccionado);
            // Sin mensaje de éxito
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaTorneosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTorneosMouseClicked
        int fila = tablaTorneos.getSelectedRow();
        if (fila >= 0) {
            try {
                idTorneoSeleccionado = Long.parseLong(tablaTorneos.getValueAt(fila, 0).toString());
                txtNombreTorneo.setText(tablaTorneos.getValueAt(fila, 1).toString());
                spinnerEdadMin.setValue(Integer.parseInt(tablaTorneos.getValueAt(fila, 2).toString()));
                spinnerEdadMax.setValue(Integer.parseInt(tablaTorneos.getValueAt(fila, 3).toString()));
                cbGenero.setSelectedItem(tablaTorneos.getValueAt(fila, 4).toString());

                // Conversión de las fechas de la tabla al JCalendar
                java.sql.Date fechaIniSQL = (java.sql.Date) tablaTorneos.getValueAt(fila, 5);
                java.sql.Date fechaFinSQL = (java.sql.Date) tablaTorneos.getValueAt(fila, 6);

                fechaIni.setDate(new java.util.Date(fechaIniSQL.getTime()));
                fechaFin.setDate(new java.util.Date(fechaFinSQL.getTime()));

            } catch (Exception ex) {
                // En C# tenías un "Error al seleccionar el torneo", aquí aplicamos el limpiaElementos() como tenías
                JOptionPane.showMessageDialog(this, "Error al cargar los torneos", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tablaTorneosMouseClicked

    private void txtNombreTorneoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTorneoKeyTyped
        if (txtNombreTorneo.getText().length() >= 50) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreTorneoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbGenero;
    private com.toedter.calendar.JCalendar fechaFin;
    private com.toedter.calendar.JCalendar fechaIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JSpinner spinnerEdadMax;
    private javax.swing.JSpinner spinnerEdadMin;
    private javax.swing.JTable tablaTorneos;
    private javax.swing.JTextField txtNombreTorneo;
    // End of variables declaration//GEN-END:variables
}
