/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.futbolito.vistas;

import com.mycompany.futbolito.dao.DetalleEquipoDAO;
import com.mycompany.futbolito.utilidades.ManejadorErroresBD;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class VistaDetalleEquipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDetalleEquipo
     */
    private List<DetalleEquipoDAO.ItemEquipo> listaEquipos = new ArrayList<>();
    private List<DetalleEquipoDAO.ItemJugador> listaJugadores = new ArrayList<>();
    
    private long idEquipoViejo = -1;
    private long idJugadorViejo = -1;

    public VistaDetalleEquipo() {
        initComponents();
        //tablaDetalleEquipo.setRowHeight(30);
        
        cargarCombos();
        cargarTabla();
        limpiarCampos();
    }

    private void cargarCombos() {
        try {
            DetalleEquipoDAO dao = new DetalleEquipoDAO();
            
            cbEquipo.removeAllItems();
            listaEquipos = dao.obtenerEquiposCombo();
            for (DetalleEquipoDAO.ItemEquipo item : listaEquipos) {
                cbEquipo.addItem(item.texto);
            }
            cbEquipo.setSelectedIndex(-1);
            
            cbJugador.removeAllItems();
            listaJugadores = dao.obtenerJugadoresCombo();
            for (DetalleEquipoDAO.ItemJugador item : listaJugadores) {
                cbJugador.addItem(item.texto);
            }
            cbJugador.setSelectedIndex(-1);
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void cargarTabla() {
        try {
            DetalleEquipoDAO dao = new DetalleEquipoDAO();
            tablaDetalleEquipo.setModel(dao.obtenerModeloDetalleEquipo());
            com.mycompany.futbolito.utilidades.UtilidadesVista.autoAjustarTodo(tablaDetalleEquipo);
            
            // Ocultamos solo las columnas de los IDs
            tablaDetalleEquipo.getColumnModel().getColumn(0).setMinWidth(0);
            tablaDetalleEquipo.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaDetalleEquipo.getColumnModel().getColumn(0).setWidth(0);
            
            tablaDetalleEquipo.getColumnModel().getColumn(1).setMinWidth(0);
            tablaDetalleEquipo.getColumnModel().getColumn(1).setMaxWidth(0);
            tablaDetalleEquipo.getColumnModel().getColumn(1).setWidth(0);
            
            tablaDetalleEquipo.getTableHeader().setReorderingAllowed(false);
            
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }

    private void limpiarCampos() {
        cbEquipo.setSelectedIndex(-1);
        cbJugador.setSelectedIndex(-1);
        idEquipoViejo = -1;
        idJugadorViejo = -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbEquipo = new javax.swing.JComboBox<>();
        cbJugador = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleEquipo = new javax.swing.JTable();

        setTitle("DetalleEquipo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Equipo:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Jugador:");

        cbEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbJugador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tablaDetalleEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaDetalleEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDetalleEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleEquipoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDetalleEquipo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cbEquipo, 0, 400, Short.MAX_VALUE)
                            .addComponent(cbJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (cbEquipo.getSelectedIndex() == -1 || cbJugador.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo y un jugador", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long idEquipoNuevo = listaEquipos.get(cbEquipo.getSelectedIndex()).idEquipo;
        long idJugadorNuevo = listaJugadores.get(cbJugador.getSelectedIndex()).idJugador;

        try {
            DetalleEquipoDAO dao = new DetalleEquipoDAO();
            
            String errorValidacion = dao.validarInscripcion(idEquipoNuevo, idJugadorNuevo, -1, -1);
            if (errorValidacion != null) {
                JOptionPane.showMessageDialog(this, errorValidacion, "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.insertarDetalle(idEquipoNuevo, idJugadorNuevo);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idEquipoViejo == -1 || idJugadorViejo == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cbEquipo.getSelectedIndex() == -1 || cbJugador.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo y un jugador", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long idEquipoNuevo = listaEquipos.get(cbEquipo.getSelectedIndex()).idEquipo;
        long idJugadorNuevo = listaJugadores.get(cbJugador.getSelectedIndex()).idJugador;

        try {
            DetalleEquipoDAO dao = new DetalleEquipoDAO();
            
            String errorValidacion = dao.validarInscripcion(idEquipoNuevo, idJugadorNuevo, idEquipoViejo, idJugadorViejo);
            if (errorValidacion != null) {
                JOptionPane.showMessageDialog(this, errorValidacion, "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.modificarDetalle(idEquipoNuevo, idJugadorNuevo, idEquipoViejo, idJugadorViejo);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idEquipoViejo == -1 || idJugadorViejo == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DetalleEquipoDAO dao = new DetalleEquipoDAO();
            dao.eliminarDetalle(idEquipoViejo, idJugadorViejo);
            cargarTabla();
            limpiarCampos();
        } catch (Exception ex) {
            ManejadorErroresBD.mostrarErrorAmigable(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaDetalleEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleEquipoMouseClicked
        int fila = tablaDetalleEquipo.getSelectedRow();
        if (fila >= 0) {
            try {
                idEquipoViejo = Long.parseLong(tablaDetalleEquipo.getValueAt(fila, 0).toString());
                idJugadorViejo = Long.parseLong(tablaDetalleEquipo.getValueAt(fila, 1).toString());
                
                // Lógica de búsqueda simple por ID
                int indexEquipo = -1;
                for (int i = 0; i < listaEquipos.size(); i++) {
                    if (listaEquipos.get(i).idEquipo == idEquipoViejo) { indexEquipo = i; break; }
                }
                
                int indexJugador = -1;
                for (int i = 0; i < listaJugadores.size(); i++) {
                    if (listaJugadores.get(i).idJugador == idJugadorViejo) { indexJugador = i; break; }
                }
                
                cbEquipo.setSelectedIndex(indexEquipo);
                cbJugador.setSelectedIndex(indexJugador);
                
            } catch (Exception ex) {
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_tablaDetalleEquipoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbEquipo;
    private javax.swing.JComboBox<String> cbJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalleEquipo;
    // End of variables declaration//GEN-END:variables
}
